# Generated by Django 3.0.3 on 2020-02-18 08:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('last_updated_on', models.DateTimeField(default=datetime.datetime(2020, 2, 18, 8, 44, 9, 352409, tzinfo=utc))),
            ],
        ),
    ]
